### ISSUE TITLE
Decouple SISTR database from sistr_cmd

### ISSUE THREAD

**Issue by peterk87** [phac-nml/sistr_cmd#25]
Database will be saved to Zenodo. Version 1.0.2 database currently backed up on Zenodo at https://zenodo.org/record/1292973#.WzD3xp1Om5P

`sistr_cmd` versions after 1.0.2 will need to download the database from Zenodo (or elsewhere) before running for the first time.

**Comment by jrober84** [comment]
sistr v. 1.1.0 has the database as a separate download which happens on first run of the tool
