### ISSUE TITLE
Error when mash distance is 1

### ISSUE THREAD

**Issue by Piplopp** [phac-nml/sistr_cmd#36]
Hello !

I'm trying to use sistr on various scaffolds from Salmonella WGS assemblies, however I stumbled upon this error.

```IndexError: list index out of range```

After looking on it it appears that this happens when you submit a sequence that results in a mash distance equals to 1. I get it how a distance of 1 is a problem but maybe raising an error and skipping the sequence would be nice.

**Comment by jrober84** [comment]
Hello,

thank you for the report, this issue has been addressed in the development branch of SISTR "sistr_cmd_update_2018" and will be merged into the main branch with the new release of SISTR.

Thanks,

James
