### ISSUE TITLE
ImportError: Can't determine version for tables

### ISSUE THREAD

**Issue by Siacm** [phac-nml/sistr_cmd#39]
Hi,

I used sistr a few months ago with this command line:

sistr -i /path/to/contigs.fa genome_name -f csv -o output.csv

and now, its not working and I get this error:
ImportError: Can't determine version for tables

Have I deleted a required module or something? I'm using sistr_cmd 1.0.2.

**Comment by peterk87** [comment]
Hi @Siacm 
It sounds like [PyTables](https://www.pytables.org/), one of the dependencies for sistr changed. 

You could try to `pip install tables` and see if that fixes your issue.

Or you could try installing sistr using [Conda](https://conda.io/en/latest/) from the [BioConda channel](https://bioconda.github.io/) with:

```bash
conda install -c bioconda sistr
```

With Conda it might be a good idea to install sistr into its own Conda environment so it doesn't have any conflicts with any other programs you might have installed:

```bash
conda create -n sistr_cmd-v1.0.2 -y sistr_cmd=1.0.2
# after your Conda env is created, activate it
conda activate sistr_cmd-v1.0.2
# run sistr
sistr --help
```

See: 
- https://anaconda.org/bioconda/sistr_cmd
- https://bioconda.github.io/recipes/sistr_cmd/README.html


There's also a Singularity image for sistr. See https://github.com/phgenomics-singularity/sistr for more info.

Hope that helps you get sistr up and running again!

**Comment by Siacm** [comment]
Ah, makes sense. Thanks Peter!
