### ISSUE TITLE
Version 1.1.0 or 2.0

### ISSUE THREAD

**Issue by andersgs** [phac-nml/sistr_cmd#42]
Hi @jrober84.

An email of yours to our Head of Enterics (Mary Valcanis)  you mentioned sistr v2 with an updated cgMLST database and O-antigen reporting logic, but I am only seeing 1.1.0. Is that what you meant?

Thank you.

Anders.

**Comment by jrober84** [comment]
Hello @andersgs,

Sorry about the confusion, for internal communication, it has been called SISTR 2, but in terms of software release it is more of a minor version bump.  The database is a very significant overhaul in terms of genomes and biomarkers included but minor tweaks to the code itself. The version that you want is 1.1.0.

-James
