### ISSUE TITLE
SISTR v1.1.1 is not compatible with pandas >= 1.1.0 due to failed EmptyDataError exception import

### ISSUE THREAD

**Issue by kbessonov1984** [phac-nml/sistr_cmd#44]
Just for future reference, in pandas 1.1.0 the `EmptyDataError` exception definition is no longer defined in `pandas/io/common.py` submodule causing `from pandas.io.common import EmptyDataError` statement, defined in `sistr/src/blast_wrapper/__init__.py`, to fail. The import statement requires to be changed to `from pandas.errors import EmptyDataError`. Could be addressed in next SISTR release. This is now handled by new conda recipe v1.1.1  build 2 restricting pandas version to <= 1.0.5

**Comment by apetkau** [comment]
Thanks @kbessonov1984 👍

**Comment by flashton2003** [comment]
Amazing! Just came across this bug, your fix worked for me thanks @kbessonov1984

**Comment by apetkau** [comment]
Just a note for this issue. If you already have a conda environment with pandas > 1.0.5 and then install sistr (via conda) it does not downgrade pandas to 1.0.5. But if you install sistr to a new environment it will install pandas 1.0.5.
