### ISSUE TITLE
Discrepant results between similar Salamae genomes

### ISSUE THREAD

**Issue by flashton2003** [phac-nml/sistr_cmd#57]
Hello,

We've isolated some subsp salamaes for one of our projects. I have a few questions about the SISTR output for these isolates: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/flashton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/flashton/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

sample | cgmlst_found_loci | cgmlst_matching_alleles | cgmlst_subspecies | o_antigen | serogroup | serovar | serovar_antigen | serovar_cgmlst | O antigen prediction | H1 antigen prediction(fliC) | H2 antigen prediction(fljB) | Predicted identification | Predicted antigenic profile | Predicted serotype | average_depth | snp_count | indel_count | N_count | reads_cov | Reference | Organism from Esmie | Salmonella genus
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CQJ13L | 330 | 129 | salamae | - | B | II 1,4,12,[27]:a:z39\|II 4:a:z39 | II 1,4,12,[27]:a:z39\|II 4:a:z39 | II 1,4,[5],12,[27]:b:[e,n,x] | 4 | a | z39 | Salmonella enterica subspecies salamae (subspecies II) | 4:a:z39 | II [1],4,12,[27]:a:z39 | 70.3072 | 40928 | 0 | 0 | 89.86 | GCF_019339485.1 |   | Salmonella species
CQJ127 | 330 | 134 | salamae | - | B | II B:-:e,n,x | II B:-:e,n,x | II 1,4,[5],12,[27]:b:[e,n,x] | 4 | z | e,n,x | Salmonella enterica subspecies salamae (subspecies II) | 4:z:e,n,x | II [1],4,12,27:z:e,n,x | 62.4964 | 40202 | 0 | 0 | 89.21 | GCF_019339485.1 | Salmonella Typhimurium | Salmonella typhimurium

</body>

</html>

1. Neither of these samples have a prediction in the o_antigen column, but when I blast them against your database, they have quite a good match (97% similarity, >99% coverage) to "304|584|1,4,12,27|B" from the wzx database. Is this match not good enough to call the O antigen? Or is there uncertainty about record 304?
2. They  are quite similar results across most fields (and for my blast results against the wxy and wxz databases), but they have different results in the output. How come?

Here are the fasta files, in case you want to dig in.

https://www.dropbox.com/scl/fi/ppkiflqyvtwrn28nah9s6/CQJ127_S25_L001.fna?rlkey=t19wktth1uguutnmqkuej3jq7&dl=0
https://www.dropbox.com/scl/fi/k4yg4iwo1k0mjdinyahx0/CQJ13L_S23_L001.fna?rlkey=woawgupve273z3b7y7tx2xipi&dl=0

Thanks,

Phil

**Comment by flashton2003** [comment]
Thanks very much, apologies for the slow response!

**Comment by kbessonov1984** [comment]
Partially addressed in new release v1.1.3

**Comment by flashton2003** [comment]
Great, thanks.
