### ISSUE TITLE
Push v1.1.2 to bioconda?

### ISSUE THREAD

**Issue by russellsmithies** [phac-nml/sistr_cmd#58]
Could someone please push v1.1.2 to bioconda?
They currently only have v1.1.1
https://anaconda.org/bioconda/sistr_cmd

thanx  :-)

**Comment by kbessonov1984** [comment]
Yes, sure. I can do that. Usually bioconda bot does that, but there might be some issues as bioconda changed rules on pinned versions and recipe rules. Thank you for highlighting this, I did not realize we are missing a conda version. Should be done this week. Thank you

**Comment by russellsmithies** [comment]
Thanx for that  :-)
I see that the only real changes were dropping some dependencies and a version number change but it will keep our users happy knowing they're on the latest version.

**Comment by kbessonov1984** [comment]
The PR was submitted to bioconda after many trial and errors due to some complex dependencies and new bioconda rules. Should be released today or tomorrow after PR merge https://github.com/bioconda/bioconda-recipes/pull/46448
